// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"NYCU-SDC/core-system-backend/internal/inbox"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockStore
func (_mock *MockStore) Count(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest) (int64, error) {
	ret := _mock.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inbox.FilterRequest) (int64, error)); ok {
		return returnFunc(ctx, userID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inbox.FilterRequest) int64); ok {
		r0 = returnFunc(ctx, userID, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *inbox.FilterRequest) error); ok {
		r1 = returnFunc(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - filter *inbox.FilterRequest
func (_e *MockStore_Expecter) Count(ctx interface{}, userID interface{}, filter interface{}) *MockStore_Count_Call {
	return &MockStore_Count_Call{Call: _e.mock.On("Count", ctx, userID, filter)}
}

func (_c *MockStore_Count_Call) Run(run func(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest)) *MockStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *inbox.FilterRequest
		if args[2] != nil {
			arg2 = args[2].(*inbox.FilterRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Count_Call) Return(n int64, err error) *MockStore_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_Count_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest) (int64, error)) *MockStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStore
func (_mock *MockStore) Get(ctx context.Context, id uuid.UUID, userID uuid.UUID) (inbox.GetRow, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 inbox.GetRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (inbox.GetRow, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) inbox.GetRow); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(inbox.GetRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockStore_Expecter) Get(ctx interface{}, id interface{}, userID interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockStore_Get_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(getRow inbox.GetRow, err error) *MockStore_Get_Call {
	_c.Call.Return(getRow, err)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (inbox.GetRow, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStore
func (_mock *MockStore) List(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest, page int, size int) ([]inbox.ListRow, error) {
	ret := _mock.Called(ctx, userID, filter, page, size)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []inbox.ListRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inbox.FilterRequest, int, int) ([]inbox.ListRow, error)); ok {
		return returnFunc(ctx, userID, filter, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inbox.FilterRequest, int, int) []inbox.ListRow); ok {
		r0 = returnFunc(ctx, userID, filter, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inbox.ListRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *inbox.FilterRequest, int, int) error); ok {
		r1 = returnFunc(ctx, userID, filter, page, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - filter *inbox.FilterRequest
//   - page int
//   - size int
func (_e *MockStore_Expecter) List(ctx interface{}, userID interface{}, filter interface{}, page interface{}, size interface{}) *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List", ctx, userID, filter, page, size)}
}

func (_c *MockStore_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest, page int, size int)) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *inbox.FilterRequest
		if args[2] != nil {
			arg2 = args[2].(*inbox.FilterRequest)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_List_Call) Return(listRows []inbox.ListRow, err error) *MockStore_List_Call {
	_c.Call.Return(listRows, err)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, filter *inbox.FilterRequest, page int, size int) ([]inbox.ListRow, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStore
func (_mock *MockStore) Update(ctx context.Context, id uuid.UUID, userID uuid.UUID, arg inbox.UserInboxMessageFilter) (inbox.UpdateRow, error) {
	ret := _mock.Called(ctx, id, userID, arg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 inbox.UpdateRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, inbox.UserInboxMessageFilter) (inbox.UpdateRow, error)); ok {
		return returnFunc(ctx, id, userID, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, inbox.UserInboxMessageFilter) inbox.UpdateRow); ok {
		r0 = returnFunc(ctx, id, userID, arg)
	} else {
		r0 = ret.Get(0).(inbox.UpdateRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, inbox.UserInboxMessageFilter) error); ok {
		r1 = returnFunc(ctx, id, userID, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - arg inbox.UserInboxMessageFilter
func (_e *MockStore_Expecter) Update(ctx interface{}, id interface{}, userID interface{}, arg interface{}) *MockStore_Update_Call {
	return &MockStore_Update_Call{Call: _e.mock.On("Update", ctx, id, userID, arg)}
}

func (_c *MockStore_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, arg inbox.UserInboxMessageFilter)) *MockStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 inbox.UserInboxMessageFilter
		if args[3] != nil {
			arg3 = args[3].(inbox.UserInboxMessageFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Update_Call) Return(updateRow inbox.UpdateRow, err error) *MockStore_Update_Call {
	_c.Call.Return(updateRow, err)
	return _c
}

func (_c *MockStore_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, arg inbox.UserInboxMessageFilter) (inbox.UpdateRow, error)) *MockStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
