# Enable debug mode (true/false)
debug: false

# The host the server binds to
host: "localhost"

# The port the server listens on
port: "8080"

# The public base URL of application, used for generating OAuth redirect URIs
base_url: "http://localhost:8080"

# Secret key used for signing tokens
secret: "your-secret-key"

# PostgreSQL connection string
database_url: "postgres://user:password@localhost:5432/dbname?sslmode=disable"

# Path to database migration source
migration_source: "file://internal/database/migrations"

# Access token expiration duration (e.g. "15m", "1h")
access_token_expiration: "15m"

# Refresh token expiration duration (e.g. "720h" for 30 days)
refresh_token_expiration: "720h"

# URL of the OpenTelemetry collector (optional)
otel_collector_url: ""

# Google OAuth credentials
google_oauth:
  client_id: "your-google-oauth-client-id"
  client_secret: "your-google-oauth-client-secret"
