database_url: "YOUR_DATABASE_URL"
base_url: "BASE_URL"
debug:
google_oauth_client_id:
google_oauth_client_secret:
nycu_oauth_client_id:
nycu_oauth_client_secret:
casbin_model_source:
casbin_policy_source:
allow_origins:
  - origin1
  - origin2
preset_user:
  'YOUR_EMAIL':
    role: admin