# vector.toml

[sources.stdin]
type = "stdin"
decoding.codec = "json"

[transforms.add_env_label]
type = "remap"
inputs = [ "stdin" ]
source = '''
.env = "dev"
'''

[sinks.to_loki]
type = "loki"
inputs = ["add_env_label"]
encoding.codec = "json"
endpoint = "http://localhost:3100"
labels = { level = "{{ level }}", app = "{{ app_name }}", version = "{{ version }}", env = "{{ env }}", traceID = "{{ trace_id }}" }

[sinks.to_console]
type = "console"
inputs = ["add_env_label"]
encoding.codec = "json"
