// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package form

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
WITH created AS (
    INSERT INTO forms (
                       title,
                       description_json,
                       description_html,
                       preview_message,
                       unit_id,
                       created_by,
                       last_editor,
                       deadline,
                       publish_time,
                       message_after_submission,
                       google_sheet_url,
                       visibility,
                       dressing_color,
                       dressing_header_font,
                       dressing_question_font,
                       dressing_text_font
                       )
    VALUES (
        $1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16
    )
    RETURNING id, title, description_json, description_html, preview_message, message_after_submission, status, unit_id, created_by, last_editor, deadline, created_at, updated_at, visibility, google_sheet_url, publish_time, cover_image_url, dressing_color, dressing_header_font, dressing_question_font, dressing_text_font
),
workflow_created AS (
    INSERT INTO workflow_versions (form_id, last_editor, workflow)
    SELECT 
        id, 
        last_editor,
        jsonb_build_array(
            jsonb_build_object(
                'id', start_node_id,
                'label', '開始表單',
                'type', 'start',
                'next', end_node_id,
                'payload', jsonb_build_object('x', 0, 'y', 0)
            ),
            jsonb_build_object(
                'id', end_node_id,
                'label', '確認/送出',
                'type', 'end',
                'payload', jsonb_build_object('x', 0, 'y', 1)
            )
        )
    FROM created, LATERAL (
        SELECT gen_random_uuid() AS start_node_id, gen_random_uuid() AS end_node_id
    ) AS node_ids
)
SELECT 
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM created f
LEFT JOIN units u ON f.unit_id = u.id
LEFT JOIN units o ON u.org_id = o.id
LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
`

type CreateParams struct {
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	PublishTime            pgtype.Timestamptz
	MessageAfterSubmission string
	GoogleSheetUrl         pgtype.Text
	Visibility             Visibility
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
}

type CreateRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Title,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.PreviewMessage,
		arg.UnitID,
		arg.CreatedBy,
		arg.LastEditor,
		arg.Deadline,
		arg.PublishTime,
		arg.MessageAfterSubmission,
		arg.GoogleSheetUrl,
		arg.Visibility,
		arg.DressingColor,
		arg.DressingHeaderFont,
		arg.DressingQuestionFont,
		arg.DressingTextFont,
	)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.PreviewMessage,
		&i.MessageAfterSubmission,
		&i.Status,
		&i.UnitID,
		&i.CreatedBy,
		&i.LastEditor,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.GoogleSheetUrl,
		&i.PublishTime,
		&i.CoverImageUrl,
		&i.DressingColor,
		&i.DressingHeaderFont,
		&i.DressingQuestionFont,
		&i.DressingTextFont,
		&i.UnitName,
		&i.OrgName,
		&i.LastEditorName,
		&i.LastEditorUsername,
		&i.LastEditorAvatarUrl,
		&i.LastEditorEmail,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM forms WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const exists = `-- name: Exists :one
SELECT EXISTS(SELECT 1 FROM forms WHERE id = $1)
`

func (q *Queries) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, exists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const get = `-- name: Get :one
SELECT 
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM forms f
LEFT JOIN units u ON f.unit_id = u.id
LEFT JOIN units o ON u.org_id = o.id
LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
WHERE f.id = $1
`

type GetRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.PreviewMessage,
		&i.MessageAfterSubmission,
		&i.Status,
		&i.UnitID,
		&i.CreatedBy,
		&i.LastEditor,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.GoogleSheetUrl,
		&i.PublishTime,
		&i.CoverImageUrl,
		&i.DressingColor,
		&i.DressingHeaderFont,
		&i.DressingQuestionFont,
		&i.DressingTextFont,
		&i.UnitName,
		&i.OrgName,
		&i.LastEditorName,
		&i.LastEditorUsername,
		&i.LastEditorAvatarUrl,
		&i.LastEditorEmail,
	)
	return i, err
}

const getByIDs = `-- name: GetByIDs :many
SELECT
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM forms f
         LEFT JOIN units u ON f.unit_id = u.id
         LEFT JOIN units o ON u.org_id = o.id
         LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
WHERE f.id = ANY($1::uuid[])
`

type GetByIDsRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) GetByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetByIDsRow, error) {
	rows, err := q.db.Query(ctx, getByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByIDsRow
	for rows.Next() {
		var i GetByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.PreviewMessage,
			&i.MessageAfterSubmission,
			&i.Status,
			&i.UnitID,
			&i.CreatedBy,
			&i.LastEditor,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.GoogleSheetUrl,
			&i.PublishTime,
			&i.CoverImageUrl,
			&i.DressingColor,
			&i.DressingHeaderFont,
			&i.DressingQuestionFont,
			&i.DressingTextFont,
			&i.UnitName,
			&i.OrgName,
			&i.LastEditorName,
			&i.LastEditorUsername,
			&i.LastEditorAvatarUrl,
			&i.LastEditorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoverImage = `-- name: GetCoverImage :one
SELECT image_data FROM form_covers WHERE form_id = $1
`

func (q *Queries) GetCoverImage(ctx context.Context, formID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCoverImage, formID)
	var image_data []byte
	err := row.Scan(&image_data)
	return image_data, err
}

const getCreator = `-- name: GetCreator :one
SELECT created_by
FROM forms
WHERE id = $1
`

func (q *Queries) GetCreator(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCreator, id)
	var created_by uuid.UUID
	err := row.Scan(&created_by)
	return created_by, err
}

const getIDBySectionID = `-- name: GetIDBySectionID :one
SELECT form_id
FROM sections
WHERE id = $1
`

func (q *Queries) GetIDBySectionID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIDBySectionID, id)
	var form_id uuid.UUID
	err := row.Scan(&form_id)
	return form_id, err
}

const getStatus = `-- name: GetStatus :one
SELECT status
FROM forms
WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id uuid.UUID) (Status, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var status Status
	err := row.Scan(&status)
	return status, err
}

const getUnitID = `-- name: GetUnitID :one
SELECT unit_id
FROM forms
WHERE id = $1
`

func (q *Queries) GetUnitID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUnitID, id)
	var unit_id pgtype.UUID
	err := row.Scan(&unit_id)
	return unit_id, err
}

const getUnitIDBySectionID = `-- name: GetUnitIDBySectionID :one
SELECT f.unit_id
FROM sections s
JOIN forms f ON s.form_id = f.id
WHERE s.id = $1
`

func (q *Queries) GetUnitIDBySectionID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUnitIDBySectionID, id)
	var unit_id pgtype.UUID
	err := row.Scan(&unit_id)
	return unit_id, err
}

const list = `-- name: List :many
SELECT 
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM forms f
LEFT JOIN units u ON f.unit_id = u.id
LEFT JOIN units o ON u.org_id = o.id
LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
WHERE ($1::status IS NULL OR f.status = $1::status)
AND ($2::visibility IS NULL OR f.visibility = $2::visibility)
AND ($3::timestamptz IS NULL OR f.deadline >= $3::timestamptz)
ORDER BY f.updated_at DESC
`

type ListParams struct {
	Status        NullStatus
	Visibility    NullVisibility
	DeadlineAfter pgtype.Timestamptz
}

type ListRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.Status, arg.Visibility, arg.DeadlineAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.PreviewMessage,
			&i.MessageAfterSubmission,
			&i.Status,
			&i.UnitID,
			&i.CreatedBy,
			&i.LastEditor,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.GoogleSheetUrl,
			&i.PublishTime,
			&i.CoverImageUrl,
			&i.DressingColor,
			&i.DressingHeaderFont,
			&i.DressingQuestionFont,
			&i.DressingTextFont,
			&i.UnitName,
			&i.OrgName,
			&i.LastEditorName,
			&i.LastEditorUsername,
			&i.LastEditorAvatarUrl,
			&i.LastEditorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByUnit = `-- name: ListByUnit :many
SELECT 
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM forms f
LEFT JOIN units u ON f.unit_id = u.id
LEFT JOIN units o ON u.org_id = o.id
LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
WHERE f.unit_id = $1
AND f.status = ANY($2::status[])
ORDER BY f.updated_at DESC
`

type ListByUnitParams struct {
	UnitID pgtype.UUID
	Status []Status
}

type ListByUnitRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) ListByUnit(ctx context.Context, arg ListByUnitParams) ([]ListByUnitRow, error) {
	rows, err := q.db.Query(ctx, listByUnit, arg.UnitID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByUnitRow
	for rows.Next() {
		var i ListByUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.PreviewMessage,
			&i.MessageAfterSubmission,
			&i.Status,
			&i.UnitID,
			&i.CreatedBy,
			&i.LastEditor,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.GoogleSheetUrl,
			&i.PublishTime,
			&i.CoverImageUrl,
			&i.DressingColor,
			&i.DressingHeaderFont,
			&i.DressingQuestionFont,
			&i.DressingTextFont,
			&i.UnitName,
			&i.OrgName,
			&i.LastEditorName,
			&i.LastEditorUsername,
			&i.LastEditorAvatarUrl,
			&i.LastEditorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patch = `-- name: Patch :one
WITH updated AS (
    UPDATE forms
    SET
        title = COALESCE($1::text, forms.title),
        description_json = COALESCE($2::jsonb, forms.description_json),
        description_html = COALESCE($3::text, forms.description_html),
        preview_message = COALESCE($4::text, forms.preview_message),
        last_editor = $5,
        deadline = COALESCE($6::timestamptz, forms.deadline),
        publish_time = COALESCE($7::timestamptz, forms.publish_time),
        message_after_submission = COALESCE($8::text, forms.message_after_submission),
        google_sheet_url = COALESCE($9::text, forms.google_sheet_url),
        visibility = COALESCE($10::visibility, forms.visibility),
        dressing_color = COALESCE($11::text, forms.dressing_color),
        dressing_header_font = COALESCE($12::text, forms.dressing_header_font),
        dressing_question_font = COALESCE($13::text, forms.dressing_question_font),
        dressing_text_font = COALESCE($14::text, forms.dressing_text_font),
        updated_at = now()
    WHERE forms.id = $15
    RETURNING id, title, description_json, description_html, preview_message, message_after_submission, status, unit_id, created_by, last_editor, deadline, created_at, updated_at, visibility, google_sheet_url, publish_time, cover_image_url, dressing_color, dressing_header_font, dressing_question_font, dressing_text_font
)
SELECT 
    f.id, f.title, f.description_json, f.description_html, f.preview_message, f.message_after_submission, f.status, f.unit_id, f.created_by, f.last_editor, f.deadline, f.created_at, f.updated_at, f.visibility, f.google_sheet_url, f.publish_time, f.cover_image_url, f.dressing_color, f.dressing_header_font, f.dressing_question_font, f.dressing_text_font,
    u.name as unit_name,
    o.name as org_name,
    usr.name as last_editor_name,
    usr.username as last_editor_username,
    usr.avatar_url as last_editor_avatar_url,
    usr.emails as last_editor_email
FROM updated f
LEFT JOIN units u ON f.unit_id = u.id
LEFT JOIN units o ON u.org_id = o.id
LEFT JOIN users_with_emails usr ON f.last_editor = usr.id
`

type PatchParams struct {
	Title                  pgtype.Text
	DescriptionJson        []byte
	DescriptionHtml        pgtype.Text
	PreviewMessage         pgtype.Text
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	PublishTime            pgtype.Timestamptz
	MessageAfterSubmission pgtype.Text
	GoogleSheetUrl         pgtype.Text
	Visibility             NullVisibility
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	ID                     uuid.UUID
}

type PatchRow struct {
	ID                     uuid.UUID
	Title                  string
	DescriptionJson        []byte
	DescriptionHtml        string
	PreviewMessage         pgtype.Text
	MessageAfterSubmission string
	Status                 Status
	UnitID                 pgtype.UUID
	CreatedBy              uuid.UUID
	LastEditor             uuid.UUID
	Deadline               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Visibility             Visibility
	GoogleSheetUrl         pgtype.Text
	PublishTime            pgtype.Timestamptz
	CoverImageUrl          pgtype.Text
	DressingColor          pgtype.Text
	DressingHeaderFont     pgtype.Text
	DressingQuestionFont   pgtype.Text
	DressingTextFont       pgtype.Text
	UnitName               pgtype.Text
	OrgName                pgtype.Text
	LastEditorName         pgtype.Text
	LastEditorUsername     pgtype.Text
	LastEditorAvatarUrl    pgtype.Text
	LastEditorEmail        interface{}
}

func (q *Queries) Patch(ctx context.Context, arg PatchParams) (PatchRow, error) {
	row := q.db.QueryRow(ctx, patch,
		arg.Title,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.PreviewMessage,
		arg.LastEditor,
		arg.Deadline,
		arg.PublishTime,
		arg.MessageAfterSubmission,
		arg.GoogleSheetUrl,
		arg.Visibility,
		arg.DressingColor,
		arg.DressingHeaderFont,
		arg.DressingQuestionFont,
		arg.DressingTextFont,
		arg.ID,
	)
	var i PatchRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.PreviewMessage,
		&i.MessageAfterSubmission,
		&i.Status,
		&i.UnitID,
		&i.CreatedBy,
		&i.LastEditor,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.GoogleSheetUrl,
		&i.PublishTime,
		&i.CoverImageUrl,
		&i.DressingColor,
		&i.DressingHeaderFont,
		&i.DressingQuestionFont,
		&i.DressingTextFont,
		&i.UnitName,
		&i.OrgName,
		&i.LastEditorName,
		&i.LastEditorUsername,
		&i.LastEditorAvatarUrl,
		&i.LastEditorEmail,
	)
	return i, err
}

const setStatus = `-- name: SetStatus :one
UPDATE forms
SET status = $2, last_editor = $3, updated_at = now()
WHERE id = $1
RETURNING id, title, description_json, description_html, preview_message, message_after_submission, status, unit_id, created_by, last_editor, deadline, created_at, updated_at, visibility, google_sheet_url, publish_time, cover_image_url, dressing_color, dressing_header_font, dressing_question_font, dressing_text_font
`

type SetStatusParams struct {
	ID         uuid.UUID
	Status     Status
	LastEditor uuid.UUID
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) (Form, error) {
	row := q.db.QueryRow(ctx, setStatus, arg.ID, arg.Status, arg.LastEditor)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.PreviewMessage,
		&i.MessageAfterSubmission,
		&i.Status,
		&i.UnitID,
		&i.CreatedBy,
		&i.LastEditor,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.GoogleSheetUrl,
		&i.PublishTime,
		&i.CoverImageUrl,
		&i.DressingColor,
		&i.DressingHeaderFont,
		&i.DressingQuestionFont,
		&i.DressingTextFont,
	)
	return i, err
}

const uploadCoverImage = `-- name: UploadCoverImage :one
WITH upsert AS (
    INSERT INTO form_covers (form_id, image_data)
    VALUES ($1, $2)
    ON CONFLICT (form_id) DO UPDATE
        SET image_data = EXCLUDED.image_data,
            updated_at = now()
    RETURNING form_id
)
UPDATE forms
SET cover_image_url = $3,
    updated_at = now()
WHERE id = (SELECT form_id FROM upsert)
RETURNING id
`

type UploadCoverImageParams struct {
	FormID        uuid.UUID
	ImageData     []byte
	CoverImageUrl pgtype.Text
}

func (q *Queries) UploadCoverImage(ctx context.Context, arg UploadCoverImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, uploadCoverImage, arg.FormID, arg.ImageData, arg.CoverImageUrl)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
