// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package highlight

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteByFormID = `-- name: DeleteByFormID :exec
DELETE FROM form_highlights
WHERE form_id = $1
`

func (q *Queries) DeleteByFormID(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByFormID, formID)
	return err
}

const getByFormID = `-- name: GetByFormID :one
SELECT id, form_id, question_id, display_title, created_at, updated_at
FROM form_highlights
WHERE form_id = $1
`

func (q *Queries) GetByFormID(ctx context.Context, formID uuid.UUID) (FormHighlight, error) {
	row := q.db.QueryRow(ctx, getByFormID, formID)
	var i FormHighlight
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.QuestionID,
		&i.DisplayTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionByFormIDAndQuestionID = `-- name: GetQuestionByFormIDAndQuestionID :one
SELECT
    q.id,
    q.type,
    q.title,
    q.metadata
FROM questions q
JOIN sections s ON s.id = q.section_id
WHERE s.form_id = $1
  AND q.id = $2
`

type GetQuestionByFormIDAndQuestionIDParams struct {
	FormID uuid.UUID
	ID     uuid.UUID
}

type GetQuestionByFormIDAndQuestionIDRow struct {
	ID       uuid.UUID
	Type     QuestionType
	Title    pgtype.Text
	Metadata []byte
}

func (q *Queries) GetQuestionByFormIDAndQuestionID(ctx context.Context, arg GetQuestionByFormIDAndQuestionIDParams) (GetQuestionByFormIDAndQuestionIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionByFormIDAndQuestionID, arg.FormID, arg.ID)
	var i GetQuestionByFormIDAndQuestionIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Metadata,
	)
	return i, err
}

const listAnswerValuesByQuestionID = `-- name: ListAnswerValuesByQuestionID :many
SELECT value
FROM answers
WHERE question_id = $1
`

func (q *Queries) ListAnswerValuesByQuestionID(ctx context.Context, questionID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listAnswerValuesByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var value []byte
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertByFormID = `-- name: UpsertByFormID :one
INSERT INTO form_highlights (form_id, question_id, display_title)
VALUES ($1, $2, $3)
ON CONFLICT (form_id)
DO UPDATE SET
    question_id = EXCLUDED.question_id,
    display_title = EXCLUDED.display_title,
    updated_at = now()
RETURNING id, form_id, question_id, display_title, created_at, updated_at
`

type UpsertByFormIDParams struct {
	FormID       uuid.UUID
	QuestionID   uuid.UUID
	DisplayTitle pgtype.Text
}

func (q *Queries) UpsertByFormID(ctx context.Context, arg UpsertByFormIDParams) (FormHighlight, error) {
	row := q.db.QueryRow(ctx, upsertByFormID, arg.FormID, arg.QuestionID, arg.DisplayTitle)
	var i FormHighlight
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.QuestionID,
		&i.DisplayTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
