// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package file

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ResourceType string

const (
	ResourceTypeFormAnswer ResourceType = "form_answer"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType
	Valid        bool // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type File struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	Data             []byte
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FileAttachment struct {
	ID           uuid.UUID
	FileID       uuid.UUID
	ResourceType ResourceType
	ResourceID   uuid.UUID
	CreatedBy    uuid.UUID
	CreatedAt    pgtype.Timestamptz
}
