// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package file

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM files
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO files (original_filename, content_type, size, data, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, original_filename, content_type, size, data, uploaded_by, created_at, updated_at
`

type CreateParams struct {
	OriginalFilename string
	ContentType      string
	Size             int64
	Data             []byte
	UploadedBy       pgtype.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (File, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OriginalFilename,
		arg.ContentType,
		arg.Size,
		arg.Data,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const existsByID = `-- name: ExistsByID :one
SELECT EXISTS(SELECT 1 FROM files WHERE id = $1)
`

func (q *Queries) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAll = `-- name: GetAll :many
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetAllParams struct {
	Limit  int32
	Offset int32
}

type GetAllRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, original_filename, content_type, size, data, uploaded_by, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByUploadedBy = `-- name: GetByUploadedBy :many
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files WHERE uploaded_by = $1 ORDER BY created_at DESC
`

type GetByUploadedByRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetByUploadedBy(ctx context.Context, uploadedBy pgtype.UUID) ([]GetByUploadedByRow, error) {
	rows, err := q.db.Query(ctx, getByUploadedBy, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByUploadedByRow
	for rows.Next() {
		var i GetByUploadedByRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadataByID = `-- name: GetMetadataByID :one
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files WHERE id = $1
`

type GetMetadataByIDRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMetadataByID(ctx context.Context, id uuid.UUID) (GetMetadataByIDRow, error) {
	row := q.db.QueryRow(ctx, getMetadataByID, id)
	var i GetMetadataByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
