// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package file

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM files
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO files (original_filename, content_type, size, data, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, original_filename, content_type, size, data, uploaded_by, created_at, updated_at
`

type CreateParams struct {
	OriginalFilename string
	ContentType      string
	Size             int64
	Data             []byte
	UploadedBy       pgtype.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (File, error) {
	row := q.db.QueryRow(ctx, create,
		arg.OriginalFilename,
		arg.ContentType,
		arg.Size,
		arg.Data,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO file_attachments (file_id, resource_type, resource_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, file_id, resource_type, resource_id, created_by, created_at
`

type CreateAttachmentParams struct {
	FileID       uuid.UUID
	ResourceType ResourceType
	ResourceID   uuid.UUID
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.FileID,
		arg.ResourceType,
		arg.ResourceID,
		arg.CreatedBy,
	)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const deleteAttachmentByID = `-- name: DeleteAttachmentByID :exec
DELETE FROM file_attachments WHERE id = $1
`

func (q *Queries) DeleteAttachmentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentByID, id)
	return err
}

const deleteAttachmentsByFileID = `-- name: DeleteAttachmentsByFileID :exec
DELETE FROM file_attachments
WHERE file_id = $1
`

func (q *Queries) DeleteAttachmentsByFileID(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByFileID, fileID)
	return err
}

const existsAttachmentByFileAndResource = `-- name: ExistsAttachmentByFileAndResource :one
SELECT EXISTS(
    SELECT 1 FROM file_attachments 
    WHERE file_id = $1 AND resource_type = $2 AND resource_id = $3
)
`

type ExistsAttachmentByFileAndResourceParams struct {
	FileID       uuid.UUID
	ResourceType ResourceType
	ResourceID   uuid.UUID
}

func (q *Queries) ExistsAttachmentByFileAndResource(ctx context.Context, arg ExistsAttachmentByFileAndResourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsAttachmentByFileAndResource, arg.FileID, arg.ResourceType, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByID = `-- name: ExistsByID :one
SELECT EXISTS(SELECT 1 FROM files WHERE id = $1)
`

func (q *Queries) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAll = `-- name: GetAll :many
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetAllParams struct {
	Limit  int32
	Offset int32
}

type GetAllRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentByFileAndResource = `-- name: GetAttachmentByFileAndResource :one
SELECT id, file_id, resource_type, resource_id, created_by, created_at
FROM file_attachments
WHERE file_id = $1
  AND resource_type = $2
  AND resource_id = $3
`

type GetAttachmentByFileAndResourceParams struct {
	FileID       uuid.UUID
	ResourceType ResourceType
	ResourceID   uuid.UUID
}

func (q *Queries) GetAttachmentByFileAndResource(ctx context.Context, arg GetAttachmentByFileAndResourceParams) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByFileAndResource, arg.FileID, arg.ResourceType, arg.ResourceID)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, file_id, resource_type, resource_id, created_by, created_at FROM file_attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, original_filename, content_type, size, data, uploaded_by, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByUploadedBy = `-- name: GetByUploadedBy :many
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files WHERE uploaded_by = $1 ORDER BY created_at DESC
`

type GetByUploadedByRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetByUploadedBy(ctx context.Context, uploadedBy pgtype.UUID) ([]GetByUploadedByRow, error) {
	rows, err := q.db.Query(ctx, getByUploadedBy, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByUploadedByRow
	for rows.Next() {
		var i GetByUploadedByRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadataByID = `-- name: GetMetadataByID :one
SELECT id, original_filename, content_type, size, uploaded_by, created_at, updated_at 
FROM files WHERE id = $1
`

type GetMetadataByIDRow struct {
	ID               uuid.UUID
	OriginalFilename string
	ContentType      string
	Size             int64
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMetadataByID(ctx context.Context, id uuid.UUID) (GetMetadataByIDRow, error) {
	row := q.db.QueryRow(ctx, getMetadataByID, id)
	var i GetMetadataByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachmentsByFileID = `-- name: ListAttachmentsByFileID :many
SELECT id, file_id, resource_type, resource_id, created_by, created_at FROM file_attachments WHERE file_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByFileID(ctx context.Context, fileID uuid.UUID) ([]FileAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAttachment
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByResource = `-- name: ListAttachmentsByResource :many
SELECT id, file_id, resource_type, resource_id, created_by, created_at FROM file_attachments
WHERE resource_type = $1 AND resource_id = $2 ORDER BY created_at ASC
`

type ListAttachmentsByResourceParams struct {
	ResourceType ResourceType
	ResourceID   uuid.UUID
}

func (q *Queries) ListAttachmentsByResource(ctx context.Context, arg ListAttachmentsByResourceParams) ([]FileAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAttachment
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFileByID = `-- name: LockFileByID :one
SELECT id
FROM files
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockFileByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockFileByID, id)
	err := row.Scan(&id)
	return id, err
}
