-- Add a monotonic sequence column to make "latest workflow version" ordering deterministic
-- even when updated_at ties inside a single transaction (now() is frozen).

ALTER TABLE workflow_versions
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Backfill existing rows with sequence values.
UPDATE workflow_versions
SET seq = DEFAULT
WHERE seq IS NULL;

ALTER TABLE workflow_versions
    ALTER COLUMN seq SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_workflow_versions_seq
    ON workflow_versions(form_id, seq DESC);

