// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package answer

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID         uuid.UUID
	ResponseID uuid.UUID
	QuestionID uuid.UUID
	Value      []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
