// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package inbox

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType string

const (
	ContentTypeText ContentType = "text"
	ContentTypeForm ContentType = "form"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType
	Valid       bool // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type InboxMessage struct {
	ID        uuid.UUID
	PostedBy  uuid.UUID
	Type      ContentType
	ContentID uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserInboxMessage struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	MessageID  uuid.UUID
	IsRead     bool
	IsStarred  bool
	IsArchived bool
}
