// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package workflow

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NodeType string

const (
	NodeTypeSection   NodeType = "section"
	NodeTypeEnd       NodeType = "end"
	NodeTypeStart     NodeType = "start"
	NodeTypeCondition NodeType = "condition"
)

func (e *NodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeType(s)
	case string:
		*e = NodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeType: %T", src)
	}
	return nil
}

type NullNodeType struct {
	NodeType NodeType
	Valid    bool // Valid is true if NodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.NodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeType), nil
}

type WorkflowVersion struct {
	ID         uuid.UUID
	FormID     uuid.UUID
	LastEditor uuid.UUID
	IsActive   bool
	Workflow   []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
