// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package view

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO views (form_id, title, "order")
VALUES ($1, $2, $3)
RETURNING id, form_id, title, locked, "order", created_at, updated_at
`

type CreateParams struct {
	FormID uuid.UUID
	Title  string
	Order  int32
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (View, error) {
	row := q.db.QueryRow(ctx, create, arg.FormID, arg.Title, arg.Order)
	var i View
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Locked,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIfUnlocked = `-- name: DeleteIfUnlocked :one
DELETE FROM views
WHERE id = $1 AND form_id = $2 AND locked = FALSE
RETURNING id, "order"
`

type DeleteIfUnlockedParams struct {
	ID     uuid.UUID
	FormID uuid.UUID
}

type DeleteIfUnlockedRow struct {
	ID    uuid.UUID
	Order int32
}

func (q *Queries) DeleteIfUnlocked(ctx context.Context, arg DeleteIfUnlockedParams) (DeleteIfUnlockedRow, error) {
	row := q.db.QueryRow(ctx, deleteIfUnlocked, arg.ID, arg.FormID)
	var i DeleteIfUnlockedRow
	err := row.Scan(&i.ID, &i.Order)
	return i, err
}

const exists = `-- name: Exists :one
SELECT EXISTS(SELECT 1 FROM views WHERE id = $1 AND form_id = $2)
`

type ExistsParams struct {
	ID     uuid.UUID
	FormID uuid.UUID
}

func (q *Queries) Exists(ctx context.Context, arg ExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, exists, arg.ID, arg.FormID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const formExists = `-- name: FormExists :one
SELECT EXISTS(SELECT 1 FROM forms WHERE id = $1)
`

func (q *Queries) FormExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, formExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const get = `-- name: Get :one
SELECT id, form_id, title, locked, "order", created_at, updated_at FROM views
WHERE id = $1 AND form_id = $2
`

type GetParams struct {
	ID     uuid.UUID
	FormID uuid.UUID
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (View, error) {
	row := q.db.QueryRow(ctx, get, arg.ID, arg.FormID)
	var i View
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Locked,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByFormID = `-- name: ListByFormID :many
SELECT id, form_id, title, locked, "order", created_at, updated_at FROM views
WHERE form_id = $1
ORDER BY "order" ASC
`

func (q *Queries) ListByFormID(ctx context.Context, formID uuid.UUID) ([]View, error) {
	rows, err := q.db.Query(ctx, listByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Title,
			&i.Locked,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitlesByFormID = `-- name: ListTitlesByFormID :many
SELECT title FROM views
WHERE form_id = $1
`

func (q *Queries) ListTitlesByFormID(ctx context.Context, formID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTitlesByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOrder = `-- name: MaxOrder :one
SELECT COALESCE(MAX("order"), -1)::integer FROM views
WHERE form_id = $1
`

func (q *Queries) MaxOrder(ctx context.Context, formID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxOrder, formID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const shiftOrders = `-- name: ShiftOrders :exec
UPDATE views
SET "order" = "order" + $3, updated_at = now()
WHERE form_id = $1 AND "order" > $2
`

type ShiftOrdersParams struct {
	FormID  uuid.UUID
	Order   int32
	Order_2 int32
}

func (q *Queries) ShiftOrders(ctx context.Context, arg ShiftOrdersParams) error {
	_, err := q.db.Exec(ctx, shiftOrders, arg.FormID, arg.Order, arg.Order_2)
	return err
}

const updateLocked = `-- name: UpdateLocked :one
UPDATE views
SET locked = $3, updated_at = now()
WHERE id = $1 AND form_id = $2
RETURNING id, form_id, title, locked, "order", created_at, updated_at
`

type UpdateLockedParams struct {
	ID     uuid.UUID
	FormID uuid.UUID
	Locked bool
}

func (q *Queries) UpdateLocked(ctx context.Context, arg UpdateLockedParams) (View, error) {
	row := q.db.QueryRow(ctx, updateLocked, arg.ID, arg.FormID, arg.Locked)
	var i View
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Locked,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
WITH shifted AS (
    UPDATE views
    SET "order" = CASE
        -- Moving down: shift views between old and new position up by 1
        WHEN $3 > (SELECT v2."order" FROM views v2 WHERE v2.id = $2 AND v2.form_id = $1)
             AND views."order" > (SELECT v2."order" FROM views v2 WHERE v2.id = $2 AND v2.form_id = $1)
             AND views."order" <= $3
        THEN views."order" - 1
        -- Moving up: shift views between new and old position down by 1
        WHEN $3 < (SELECT v2."order" FROM views v2 WHERE v2.id = $2 AND v2.form_id = $1)
             AND views."order" >= $3
             AND views."order" < (SELECT v2."order" FROM views v2 WHERE v2.id = $2 AND v2.form_id = $1)
        THEN views."order" + 1
        ELSE views."order"
    END,
    updated_at = now()
    WHERE views.form_id = $1 AND views.id != $2
    RETURNING views.id
),
updated AS (
    UPDATE views
    SET "order" = $3, updated_at = now()
    WHERE id = $2 AND form_id = $1
    RETURNING id, form_id, title, locked, "order", created_at, updated_at
)
SELECT id, form_id, title, locked, "order", created_at, updated_at FROM updated
`

type UpdateOrderParams struct {
	FormID uuid.UUID
	ID     uuid.UUID
	Order  int32
}

type UpdateOrderRow struct {
	ID        uuid.UUID
	FormID    uuid.UUID
	Title     string
	Locked    bool
	Order     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.FormID, arg.ID, arg.Order)
	var i UpdateOrderRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Locked,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTitle = `-- name: UpdateTitle :one
UPDATE views
SET title = $3, updated_at = now()
WHERE id = $1 AND form_id = $2
RETURNING id, form_id, title, locked, "order", created_at, updated_at
`

type UpdateTitleParams struct {
	ID     uuid.UUID
	FormID uuid.UUID
	Title  string
}

func (q *Queries) UpdateTitle(ctx context.Context, arg UpdateTitleParams) (View, error) {
	row := q.db.QueryRow(ctx, updateTitle, arg.ID, arg.FormID, arg.Title)
	var i View
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Locked,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
