networks:
  core_system_$VERSION:
    driver: bridge
  traefik:
    external: true

services:
  backend:
    image: nycusdc/core-system-backend:$VERSION
    container_name: core-system-backend-$VERSION
    ports:
      - '$PORT:8080'
    networks:
      - core_system_$VERSION
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HOST: "0.0.0.0"
      DATABASE_URL: postgres://postgres:password@postgres:5432/core_system?sslmode=disable
      MIGRATION_SOURCE: file:///app/migrations
      OTEL_COLLECTOR_URL: 10.140.0.3:4317
    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.core-system-backend.rule=Host(`api.snapshot.core-system.sdc.nycu.club`)"
      - "traefik.http.routers.core-system-backend.entrypoints=websecure"
      - "traefik.http.routers.core-system-backend.tls=true"
      - "traefik.http.routers.core-system-backend.tls.certresolver=cloudflare"
    
    
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core_system
    networks:
      - core_system_$VERSION