// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package question

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionType string

const (
	QuestionTypeShortText              QuestionType = "short_text"
	QuestionTypeLongText               QuestionType = "long_text"
	QuestionTypeSingleChoice           QuestionType = "single_choice"
	QuestionTypeMultipleChoice         QuestionType = "multiple_choice"
	QuestionTypeDate                   QuestionType = "date"
	QuestionTypeDropdown               QuestionType = "dropdown"
	QuestionTypeDetailedMultipleChoice QuestionType = "detailed_multiple_choice"
	QuestionTypeUploadFile             QuestionType = "upload_file"
	QuestionTypeLinearScale            QuestionType = "linear_scale"
	QuestionTypeRating                 QuestionType = "rating"
	QuestionTypeRanking                QuestionType = "ranking"
	QuestionTypeOauthConnect           QuestionType = "oauth_connect"
	QuestionTypeHyperlink              QuestionType = "hyperlink"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType
	Valid        bool // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type Section struct {
	ID              uuid.UUID
	FormID          uuid.UUID
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
