// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
WITH inserted AS (
    INSERT INTO questions (section_id, required, type, title, description_json, description_html, metadata, "order", source_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, section_id, required, type, title, description_json, description_html, metadata, "order", source_id, created_at, updated_at
)
SELECT 
    i.id,
    i.section_id,
    i.required,
    i.type,
    i.title,
    i.description_json,
    i.description_html,
    i.metadata,
    i."order",
    i.source_id,
    i.created_at,
    i.updated_at,
    s.form_id
FROM inserted i
JOIN sections s ON i.section_id = s.id
`

type CreateParams struct {
	SectionID       uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	Order           int32
	SourceID        pgtype.UUID
}

type CreateRow struct {
	ID              uuid.UUID
	SectionID       uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	Order           int32
	SourceID        pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FormID          uuid.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create,
		arg.SectionID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.Metadata,
		arg.Order,
		arg.SourceID,
	)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const deleteAndReorder = `-- name: DeleteAndReorder :exec
WITH deleted_row AS (
    DELETE FROM questions q
    WHERE q.section_id = $1 AND q.id = $2
    RETURNING "order" as old_order, section_id
)
UPDATE questions q
SET "order" = q."order" - 1
FROM deleted_row
WHERE q.section_id = deleted_row.section_id
  AND "order" > deleted_row.old_order
`

type DeleteAndReorderParams struct {
	SectionID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteAndReorder(ctx context.Context, arg DeleteAndReorderParams) error {
	_, err := q.db.Exec(ctx, deleteAndReorder, arg.SectionID, arg.ID)
	return err
}

const get = `-- name: Get :one
SELECT 
    q.id,
    q.section_id,
    q.required,
    q.type,
    q.title,
    q.description_json,
    q.description_html,
    q.metadata,
    q."order",
    q.source_id,
    q.created_at,
    q.updated_at,
    s.form_id
FROM questions q
JOIN sections s ON q.section_id = s.id
WHERE q.id = $1
`

type GetRow struct {
	ID              uuid.UUID
	SectionID       uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	Order           int32
	SourceID        pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FormID          uuid.UUID
}

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const listOrderBySectionID = `-- name: ListOrderBySectionID :many
SELECT id, "order"
FROM questions
WHERE section_id = $1
ORDER BY "order" ASC
`

type ListOrderBySectionIDRow struct {
	ID    uuid.UUID
	Order int32
}

func (q *Queries) ListOrderBySectionID(ctx context.Context, sectionID uuid.UUID) ([]ListOrderBySectionIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderBySectionID, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderBySectionIDRow
	for rows.Next() {
		var i ListOrderBySectionIDRow
		if err := rows.Scan(&i.ID, &i.Order); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByFormID = `-- name: ListSectionsByFormID :many
SELECT id, form_id, title, description_json, description_html, created_at, updated_at
FROM sections
WHERE form_id = $1
`

func (q *Queries) ListSectionsByFormID(ctx context.Context, formID uuid.UUID) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSectionsByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Title,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsWithAnswersByFormID = `-- name: ListSectionsWithAnswersByFormID :many
SELECT
    s.id as section_id,
    s.form_id,
    s.title,
    s.description_json,
    s.description_html,
    s.created_at,
    s.updated_at,
    q.id,
    q.required,
    q.type,
    q.title as question_title,
    q.description_json as question_description_json,
    q.description_html as question_description_html,
    q.metadata,
    q."order",
    q.source_id,
    q.created_at as question_created_at,
    q.updated_at as question_updated_at
FROM sections s
LEFT JOIN questions q ON s.id = q.section_id
WHERE s.form_id = $1
ORDER BY
    s.id ASC,
    q."order" ASC
`

type ListSectionsWithAnswersByFormIDRow struct {
	SectionID               uuid.UUID
	FormID                  uuid.UUID
	Title                   pgtype.Text
	DescriptionJson         []byte
	DescriptionHtml         string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	ID                      pgtype.UUID
	Required                pgtype.Bool
	Type                    NullQuestionType
	QuestionTitle           pgtype.Text
	QuestionDescriptionJson []byte
	QuestionDescriptionHtml pgtype.Text
	Metadata                []byte
	Order                   pgtype.Int4
	SourceID                pgtype.UUID
	QuestionCreatedAt       pgtype.Timestamptz
	QuestionUpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListSectionsWithAnswersByFormID(ctx context.Context, formID uuid.UUID) ([]ListSectionsWithAnswersByFormIDRow, error) {
	rows, err := q.db.Query(ctx, listSectionsWithAnswersByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionsWithAnswersByFormIDRow
	for rows.Next() {
		var i ListSectionsWithAnswersByFormIDRow
		if err := rows.Scan(
			&i.SectionID,
			&i.FormID,
			&i.Title,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.Required,
			&i.Type,
			&i.QuestionTitle,
			&i.QuestionDescriptionJson,
			&i.QuestionDescriptionHtml,
			&i.Metadata,
			&i.Order,
			&i.SourceID,
			&i.QuestionCreatedAt,
			&i.QuestionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT id, type
FROM questions
WHERE id = ANY($1::uuid[])
`

type ListTypesRow struct {
	ID   uuid.UUID
	Type QuestionType
}

func (q *Queries) ListTypes(ctx context.Context, dollar_1 []uuid.UUID) ([]ListTypesRow, error) {
	rows, err := q.db.Query(ctx, listTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTypesRow
	for rows.Next() {
		var i ListTypesRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sectionExists = `-- name: SectionExists :one
SELECT EXISTS(SELECT 1 FROM sections WHERE id = $1)
`

func (q *Queries) SectionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sectionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const shiftOrdersForInsert = `-- name: ShiftOrdersForInsert :exec
UPDATE questions
SET "order" = "order" + 1, updated_at = now()
WHERE section_id = $1 AND "order" >= $2
`

type ShiftOrdersForInsertParams struct {
	SectionID uuid.UUID
	Order     int32
}

func (q *Queries) ShiftOrdersForInsert(ctx context.Context, arg ShiftOrdersForInsertParams) error {
	_, err := q.db.Exec(ctx, shiftOrdersForInsert, arg.SectionID, arg.Order)
	return err
}

const update = `-- name: Update :one
WITH updated AS (
    UPDATE questions
    SET required = $3, type = $4, title = $5, description_json = $6, description_html = $7, metadata = $8, source_id = $9, updated_at = now()
    WHERE questions.section_id = $1 AND questions.id = $2
    RETURNING id, section_id, required, type, title, description_json, description_html, metadata, "order", source_id, created_at, updated_at
)
SELECT 
    u.id,
    u.section_id,
    u.required,
    u.type,
    u.title,
    u.description_json,
    u.description_html,
    u.metadata,
    u."order",
    u.source_id,
    u.created_at,
    u.updated_at,
    s.form_id
FROM updated u
JOIN sections s ON u.section_id = s.id
`

type UpdateParams struct {
	SectionID       uuid.UUID
	ID              uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	SourceID        pgtype.UUID
}

type UpdateRow struct {
	ID              uuid.UUID
	SectionID       uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	Order           int32
	SourceID        pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FormID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (UpdateRow, error) {
	row := q.db.QueryRow(ctx, update,
		arg.SectionID,
		arg.ID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.Metadata,
		arg.SourceID,
	)
	var i UpdateRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
WITH shifted AS (
    UPDATE questions
    SET "order" = CASE
        -- Moving down: shift questions between old and new position up
        WHEN $3 > (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1) 
             AND questions."order" > (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1) 
             AND questions."order" <= $3
        THEN questions."order" - 1
        -- Moving up: shift questions between new and old position down
        WHEN $3 < (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1)
             AND questions."order" >= $3
             AND questions."order" < (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1)
        THEN questions."order" + 1
        ELSE questions."order"
    END,
    updated_at = now()
    WHERE questions.section_id = $1 AND questions.id != $2
    RETURNING questions.id
),
updated AS (
    UPDATE questions q
    SET "order" = $3, updated_at = now()
    WHERE q.id = $2 AND q.section_id = $1
    RETURNING q.id, q.section_id, q.required, q.type, q.title, q.description_json, q.description_html, q.metadata, q."order", q.source_id, q.created_at, q.updated_at
)
SELECT 
    u.id,
    u.section_id,
    u.required,
    u.type,
    u.title,
    u.description_json,
    u.description_html,
    u.metadata,
    u."order",
    u.source_id,
    u.created_at,
    u.updated_at,
    s.form_id
FROM updated u
JOIN sections s ON u.section_id = s.id
`

type UpdateOrderParams struct {
	SectionID uuid.UUID
	ID        uuid.UUID
	Order     int32
}

type UpdateOrderRow struct {
	ID              uuid.UUID
	SectionID       uuid.UUID
	Required        bool
	Type            QuestionType
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml string
	Metadata        []byte
	Order           int32
	SourceID        pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FormID          uuid.UUID
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.SectionID, arg.ID, arg.Order)
	var i UpdateOrderRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections
SET title = $1,
    description_json = COALESCE($2::jsonb, sections.description_json),
    description_html = COALESCE($3::text, sections.description_html),
    updated_at = now()
WHERE id = $4 AND form_id = $5
RETURNING id, form_id, title, description_json, description_html, created_at, updated_at
`

type UpdateSectionParams struct {
	Title           pgtype.Text
	DescriptionJson []byte
	DescriptionHtml pgtype.Text
	ID              uuid.UUID
	FormID          uuid.UUID
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.Title,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.ID,
		arg.FormID,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
