// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package user

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO users (name, username, avatar_url, role, is_onboarded)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, username, avatar_url, role, is_onboarded, created_at, updated_at
`

type CreateParams struct {
	Name        pgtype.Text
	Username    pgtype.Text
	AvatarUrl   pgtype.Text
	Role        []string
	IsOnboarded bool
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Username,
		arg.AvatarUrl,
		arg.Role,
		arg.IsOnboarded,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Role,
		&i.IsOnboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuth = `-- name: CreateAuth :one
INSERT INTO auth (user_id, provider, provider_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_id, created_at, updated_at
`

type CreateAuthParams struct {
	UserID     uuid.UUID
	Provider   string
	ProviderID string
}

func (q *Queries) CreateAuth(ctx context.Context, arg CreateAuthParams) (Auth, error) {
	row := q.db.QueryRow(ctx, createAuth, arg.UserID, arg.Provider, arg.ProviderID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWithID = `-- name: CreateWithID :one
INSERT INTO users (id, name, username, avatar_url, role, is_onboarded)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, username, avatar_url, role, is_onboarded, created_at, updated_at
`

type CreateWithIDParams struct {
	ID          uuid.UUID
	Name        pgtype.Text
	Username    pgtype.Text
	AvatarUrl   pgtype.Text
	Role        []string
	IsOnboarded bool
}

func (q *Queries) CreateWithID(ctx context.Context, arg CreateWithIDParams) (User, error) {
	row := q.db.QueryRow(ctx, createWithID,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.AvatarUrl,
		arg.Role,
		arg.IsOnboarded,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Role,
		&i.IsOnboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const get = `-- name: Get :one
SELECT id, name, username, avatar_url, role, is_onboarded, created_at, updated_at, emails
FROM users_with_emails
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (UsersWithEmail, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i UsersWithEmail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Role,
		&i.IsOnboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Emails,
	)
	return i, err
}

const getEmails = `-- name: GetEmails :many
SELECT user_emails.value as email FROM user_emails WHERE user_id = $1 ORDER BY value
`

func (q *Queries) GetEmails(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIDByAuth = `-- name: GetIDByAuth :one
SELECT user_id FROM auth WHERE provider = $1 AND provider_id = $2
`

type GetIDByAuthParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) GetIDByAuth(ctx context.Context, arg GetIDByAuthParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIDByAuth, arg.Provider, arg.ProviderID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getIDByEmail = `-- name: GetIDByEmail :one
SELECT user_id FROM user_emails WHERE value = $1
`

func (q *Queries) GetIDByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIDByEmail, email)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getIDByEmailForUpdate = `-- name: GetIDByEmailForUpdate :one
SELECT user_id FROM user_emails WHERE value = $1 FOR UPDATE
`

func (q *Queries) GetIDByEmailForUpdate(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIDByEmailForUpdate, email)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getWithEarliestProviderByEmail = `-- name: GetWithEarliestProviderByEmail :one
SELECT u.id, u.name, a.provider, a.provider_id
FROM user_emails e
         JOIN users u ON e.user_id = u.id
         LEFT JOIN auth a ON a.user_id = u.id
WHERE e.value = $1
ORDER BY a.created_at ASC
    LIMIT 1
`

type GetWithEarliestProviderByEmailRow struct {
	ID         uuid.UUID
	Name       pgtype.Text
	Provider   pgtype.Text
	ProviderID pgtype.Text
}

func (q *Queries) GetWithEarliestProviderByEmail(ctx context.Context, email string) (GetWithEarliestProviderByEmailRow, error) {
	row := q.db.QueryRow(ctx, getWithEarliestProviderByEmail, email)
	var i GetWithEarliestProviderByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE users
SET name = $1, username = $2, avatar_url = $3, is_onboarded = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, name, username, avatar_url, role, is_onboarded, created_at, updated_at
`

type UpdateParams struct {
	Name        pgtype.Text
	Username    pgtype.Text
	AvatarUrl   pgtype.Text
	IsOnboarded bool
	ID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, update,
		arg.Name,
		arg.Username,
		arg.AvatarUrl,
		arg.IsOnboarded,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.AvatarUrl,
		&i.Role,
		&i.IsOnboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmail = `-- name: UpsertEmail :exec
INSERT INTO user_emails (user_id, value)
VALUES ($1, $2)
ON CONFLICT (value) DO UPDATE SET updated_at = now()
`

type UpsertEmailParams struct {
	UserID uuid.UUID
	Email  string
}

func (q *Queries) UpsertEmail(ctx context.Context, arg UpsertEmailParams) error {
	_, err := q.db.Exec(ctx, upsertEmail, arg.UserID, arg.Email)
	return err
}
