// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package unit

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UnitRole string

const (
	UnitRoleAdmin  UnitRole = "admin"
	UnitRoleMember UnitRole = "member"
)

func (e *UnitRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitRole(s)
	case string:
		*e = UnitRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitRole: %T", src)
	}
	return nil
}

type NullUnitRole struct {
	UnitRole UnitRole
	Valid    bool // Valid is true if UnitRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitRole) Scan(value interface{}) error {
	if value == nil {
		ns.UnitRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitRole), nil
}

type UnitType string

const (
	UnitTypeOrganization UnitType = "organization"
	UnitTypeUnit         UnitType = "unit"
)

func (e *UnitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitType(s)
	case string:
		*e = UnitType(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitType: %T", src)
	}
	return nil
}

type NullUnitType struct {
	UnitType UnitType
	Valid    bool // Valid is true if UnitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitType) Scan(value interface{}) error {
	if value == nil {
		ns.UnitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitType), nil
}

type Unit struct {
	ID          uuid.UUID
	OrgID       pgtype.UUID
	ParentID    pgtype.UUID
	Type        UnitType
	Name        pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UnitMember struct {
	UnitID   uuid.UUID
	MemberID uuid.UUID
	Role     UnitRole
}
