// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package response

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ResponseProgress string

const (
	ResponseProgressDraft     ResponseProgress = "draft"
	ResponseProgressSubmitted ResponseProgress = "submitted"
)

func (e *ResponseProgress) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResponseProgress(s)
	case string:
		*e = ResponseProgress(s)
	default:
		return fmt.Errorf("unsupported scan type for ResponseProgress: %T", src)
	}
	return nil
}

type NullResponseProgress struct {
	ResponseProgress ResponseProgress
	Valid            bool // Valid is true if ResponseProgress is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResponseProgress) Scan(value interface{}) error {
	if value == nil {
		ns.ResponseProgress, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResponseProgress.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResponseProgress) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResponseProgress), nil
}

type FormResponse struct {
	ID          uuid.UUID
	FormID      uuid.UUID
	SubmittedBy uuid.UUID
	SubmittedAt pgtype.Timestamptz
	Progress    ResponseProgress
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
