// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package response

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO form_responses (form_id, submitted_by)
VALUES ($1, $2)
RETURNING id, form_id, submitted_by, submitted_at, progress, created_at, updated_at
`

type CreateParams struct {
	FormID      uuid.UUID
	SubmittedBy uuid.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (FormResponse, error) {
	row := q.db.QueryRow(ctx, create, arg.FormID, arg.SubmittedBy)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Progress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM form_responses
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const exists = `-- name: Exists :one
SELECT EXISTS(SELECT 1 FROM form_responses WHERE form_id = $1 AND submitted_by = $2)
`

type ExistsParams struct {
	FormID      uuid.UUID
	SubmittedBy uuid.UUID
}

func (q *Queries) Exists(ctx context.Context, arg ExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, exists, arg.FormID, arg.SubmittedBy)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const get = `-- name: Get :one
SELECT id, form_id, submitted_by, submitted_at, progress, created_at, updated_at FROM form_responses
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (FormResponse, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Progress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByFormIDAndSubmittedBy = `-- name: GetByFormIDAndSubmittedBy :one
SELECT id, form_id, submitted_by, submitted_at, progress, created_at, updated_at FROM form_responses
WHERE form_id = $1 AND submitted_by = $2
`

type GetByFormIDAndSubmittedByParams struct {
	FormID      uuid.UUID
	SubmittedBy uuid.UUID
}

func (q *Queries) GetByFormIDAndSubmittedBy(ctx context.Context, arg GetByFormIDAndSubmittedByParams) (FormResponse, error) {
	row := q.db.QueryRow(ctx, getByFormIDAndSubmittedBy, arg.FormID, arg.SubmittedBy)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Progress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByFormID = `-- name: ListByFormID :many
SELECT id, form_id, submitted_by, submitted_at, progress, created_at, updated_at FROM form_responses
WHERE form_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListByFormID(ctx context.Context, formID uuid.UUID) ([]FormResponse, error) {
	rows, err := q.db.Query(ctx, listByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormResponse
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.Progress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBySubmittedBy = `-- name: ListBySubmittedBy :many
SELECT id, form_id, submitted_by, submitted_at, progress, created_at, updated_at FROM form_responses
WHERE submitted_by = $1
ORDER BY submitted_at DESC NULLS LAST
`

func (q *Queries) ListBySubmittedBy(ctx context.Context, submittedBy uuid.UUID) ([]FormResponse, error) {
	rows, err := q.db.Query(ctx, listBySubmittedBy, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormResponse
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.Progress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE form_responses
SET updated_at = now(), progress = $2
WHERE id = $1
`

type UpdateParams struct {
	ID       uuid.UUID
	Progress ResponseProgress
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update, arg.ID, arg.Progress)
	return err
}
